
name-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Enhancements'
    label: 'enhancement'
  - title: 'Bug fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Dependency updates'
    label: 'dependency-update'
change-template: '- $TITLE: #$NUMBER by @$AUTHOR'
template: |
  $CHANGES