addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager"       % "1.8.1")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"              % "0.9.26")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"              % "2.4.2")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"                   % "0.4.0")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"               % "0.5.2")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"             % "0.10.0")
addSbtPlugin("ch.epfl.scala"      % "sbt-bloop"                 % "1.4.8")
addSbtPlugin("com.github.cb372"   % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin"           % "0.8.1")
//
addSbtPlugin("com.typesafe.sbt"   % "sbt-git"                   % "1.0.0")
addSbtPlugin("com.eed3si9n"       % "sbt-assembly"              % "0.15.0")
addSbtPlugin("se.marcuslonnberg"  % "sbt-docker"                % "1.8.2")
addSbtPlugin("au.com.onegeek" % "sbt-dotenv" % "2.1.204")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")