name: CI

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
      - name: Run scalafix and scalafmt
        run: sbt ';scalafixAll --check ;scalafmtCheckAll '

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
      - name: Run tests
        run: sbt clean test